# Generated by Django 5.0.1 on 2024-01-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jadidlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hikmatli_sozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('jadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadidlar.jadid')),
            ],
            options={
                'verbose_name': 'Hikmatli soz',
                'verbose_name_plural': 'Hikmatli sozlar',
            },
        ),
    ]
