# Generated by Django 5.0.1 on 2024-01-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikmatli_sozlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikmatli_sozlar',
            name='text',
            field=models.TextField(verbose_name='Hikmatli soz'),
        ),
    ]
