# Generated by Django 5.0.1 on 2024-01-12 06:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikmatli_sozlar', '0002_alter_hikmatli_sozlar_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikmatli_sozlar',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Hikmatli soz'),
        ),
    ]
