# Generated by Django 5.0.1 on 2024-01-12 10:29

import manbalar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manbalar', '0003_alter_rasmlar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasmlar',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[manbalar.models.validate_image_extension]),
        ),
    ]
