# Generated by Django 5.0.1 on 2024-01-12 11:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanferensiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='nomi')),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'verbose_name': 'Kanferensiya',
                'verbose_name_plural': 'Kanferensiyalar',
            },
        ),
        migrations.CreateModel(
            name='Seminarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='nomi')),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'verbose_name': 'Seminar',
                'verbose_name_plural': 'Seminarlar',
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='nomi')),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
