# Generated by Django 5.0.1 on 2024-01-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jadidlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hikmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='hikmatli soz')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hikmat',
                'verbose_name_plural': 'Hikmatlar',
            },
        ),
        migrations.CreateModel(
            name='Hujjatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Hotiralar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('file', models.FileField(upload_to='asarlar')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('jadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadidlar.jadid')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hujjatlar.hujjatlar')),
            ],
            options={
                'verbose_name': 'Hotira',
                'verbose_name_plural': 'Hotiralar',
            },
        ),
        migrations.CreateModel(
            name='Dissertatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('file', models.FileField(upload_to='dissertations')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hujjatlar.hujjatlar')),
            ],
            options={
                'verbose_name': 'Dissertatsiya',
                'verbose_name_plural': 'Dissertatsiyalar',
            },
        ),
        migrations.CreateModel(
            name='Asarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('file', models.FileField(upload_to='asarlar')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('jadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadidlar.jadid')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hujjatlar.hujjatlar')),
            ],
            options={
                'verbose_name': 'Asar',
                'verbose_name_plural': 'Asarlar',
            },
        ),
        migrations.CreateModel(
            name='Arxiv_hujjatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('arxiv', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='archives')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hujjatlar.hujjatlar')),
            ],
            options={
                'verbose_name': 'Arxiv_hujjat',
                'verbose_name_plural': 'Arxiv_hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Maqolalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('file', models.FileField(upload_to='asarlar')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('jadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadidlar.jadid')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hujjatlar.hujjatlar')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Sherlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('file', models.FileField(upload_to='asarlar')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('jadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadidlar.jadid')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hujjatlar.hujjatlar')),
            ],
            options={
                'verbose_name': 'Sher',
                'verbose_name_plural': 'Sherlar',
            },
        ),
        migrations.CreateModel(
            name='Tadqiqotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('file', models.FileField(upload_to='asarlar')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('jadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadidlar.jadid')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hujjatlar.hujjatlar')),
            ],
            options={
                'verbose_name': 'Tadqiqot',
                'verbose_name_plural': 'Tadqiqotlar',
            },
        ),
    ]
