# Generated by Django 5.0.1 on 2024-01-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arxiv_hujjatlar',
            old_name='category',
            new_name='hujjatlar',
        ),
        migrations.RenameField(
            model_name='dissertatsiya',
            old_name='category',
            new_name='hujjatlar',
        ),
    ]
