# Generated by Django 5.0.1 on 2024-01-12 06:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0003_alter_arxiv_hujjatlar_file_alter_asarlar_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikmatlar',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='hikmatli soz'),
        ),
    ]
