# Generated by Django 5.0.1 on 2024-01-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0004_alter_hikmatlar_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertatsiya',
            name='hujjatlar',
        ),
        migrations.RemoveField(
            model_name='tadqiqotlar',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='sherlar',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='hotiralar',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='asarlar',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='arxiv_hujjatlar',
            name='hujjatlar',
        ),
        migrations.RemoveField(
            model_name='maqolalar',
            name='sub',
        ),
        migrations.DeleteModel(
            name='Hujjatlar',
        ),
    ]
