# Generated by Django 5.0.1 on 2024-01-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0005_remove_dissertatsiya_hujjatlar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arxiv_hujjatlar',
            name='arxiv',
        ),
    ]
