# Generated by Django 5.0.1 on 2024-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydali_havolalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='nomi')),
                ('link', models.TextField()),
                ('logo_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Foydali_havola',
                'verbose_name_plural': 'Foydali_havolalar',
            },
        ),
    ]
