# Generated by Django 5.0.1 on 2024-01-12 06:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydali_havolalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydali_havolalar',
            name='link',
            field=ckeditor.fields.RichTextField(verbose_name='link'),
        ),
    ]
