# Generated by Django 5.0.1 on 2024-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ishtirokchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Ishtirokchi',
                'verbose_name_plural': 'Ishtirokchilar',
            },
        ),
    ]
