# Generated by Django 5.0.1 on 2024-01-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishtirokchilar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishtirokchilar',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
