# Generated by Django 5.0.1 on 2024-01-12 12:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sahifalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sahifa nomi')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Matn')),
                ('file', models.FileField(upload_to='files/', verbose_name='Fayl')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Sahifa',
                'verbose_name_plural': 'Sahifalar',
            },
        ),
    ]
