# Generated by Django 5.0.1 on 2024-01-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahifalar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sahifalar',
            name='create',
        ),
        migrations.RemoveField(
            model_name='sahifalar',
            name='update',
        ),
    ]
