# Generated by Django 5.0.1 on 2024-01-12 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahifalar', '0002_remove_sahifalar_create_remove_sahifalar_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahifalar',
            name='create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sahifalar',
            name='update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
