# Generated by Django 5.0.1 on 2024-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahifalar', '0003_sahifalar_create_sahifalar_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahifalar',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sahifalar',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
