# Generated by Django 5.0.1 on 2024-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahifalar', '0004_alter_sahifalar_create_alter_sahifalar_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahifalar',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='sahifalar',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
