# Generated by Django 5.0.1 on 2024-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('die_day', models.DateField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='jadid')),
                ('order', models.IntegerField(default=0)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Jadid',
                'verbose_name_plural': 'Jadidlar',
            },
        ),
    ]
