# Generated by Django 5.0.1 on 2024-01-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadidlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadid',
            name='image',
            field=models.ImageField(upload_to='image/jadid'),
        ),
    ]
