# Generated by Django 5.0.1 on 2024-01-12 06:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadidlar', '0002_alter_jadid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadid',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
