# Generated by Django 5.0.1 on 2024-01-12 14:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadidlar', '0003_alter_jadid_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadid',
            name='bio_oz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='jadid',
            name='bio_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='jadid',
            name='fullname_oz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jadid',
            name='fullname_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
